# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"
  config.vm.network "public_network"
  # Web server
  config.vm.define "Docker" do |vg|
    vg.vm.hostname = "Docker-dev"
    # static ip address
    vg.vm.network :private_network, ip: "192.168.33.125"
    vg.vm.network :forwarded_port, guest: 80, host: 8050
  end
end