# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"
  config.vm.network "public_network"
  # Web server
  config.vm.define "Nexus" do |vg|
    vg.vm.hostname = "Nexus-dev"
    # static ip address
    vg.vm.network :private_network, ip: "192.168.33.150"
    vg.vm.network :forwarded_port, guest: 8081, host: 8090
  end
end